# Generated by Django 5.0.1 on 2026-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0002_remove_booking_time_slot_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('AIML', 'AI & ML'), ('ECE', 'Electronics'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil')], max_length=10),
        ),
    ]
