# Generated by Django 5.0.1 on 2026-02-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0003_staffprofile_year_alter_staffprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_REP', 'Pending Class Rep'), ('PENDING_STAFF', 'Pending Faculty Advisor'), ('STAFF_APPROVED', 'Pending Admin'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
